### ISSUE TITLE
Styles should not be global and should be scoped to the datepicker

### ISSUE THREAD

**Issue by on3iro** [rnwonder/solid-date-picker#10]
Hi,

we've found another issue: right now the `button:hover`-style is globally set, which messes with the styling of the rest of the application. Of course this can be mitigated by overwriting that particular style, but I think that a library should not interfere with the application in such a way. The best way to fix this would probably to just give the date picker button a custom class and not style the element directly. If you want I could make a PR for this.

Thanks :)

**Comment by rnwonder** [comment]
Oh true forgot about that. I'll fix it now

**Comment by rnwonder** [comment]
Fixed upgrade to the latest version

**Comment by rnwonder** [comment]
closing this
