### ISSUE TITLE
Global styles is applied by the library...

### ISSUE THREAD

**Issue by carere** [rnwonder/solid-date-picker#13]
**Describe the bug**
When using the library, I can see that global styles are applied (it breaks my CSS).
The global styles concern border-color. It's the first line of the minified CSS shipped with the library.

**To Reproduce**
Create a project with the component, and look the HTML file, you'll see the CSS imported from the library.
In there, you can see that the first line of the minified CSS, look for:
`*, :before, :after`

**Expected behavior**
The library should not define global CSS !!! It's a big no-go...

**Additional Context**
I think the problem comes from DaisyUI which may declare global variables

**Comment by rnwonder** [comment]
Yeah its from daisyUI can't do much on this for now. I'll look at it in about a weeks time at the latest. If you can fix it before then please do and raise a pr

**Comment by Azq2** [comment]
Currently library is unusable :(

**Comment by rnwonder** [comment]
> Currently library is unusable :( 

Sorry to hear that but I have alot on my hands currently. If you can hopefully take a look at it maybe reach out to daisy ui on a fix then implement it. Raise a pr then I will merge and your good to go. Will take me a long time to get to fixing this.

**Comment by rnwonder** [comment]
@carere @Azq2 upgrade to the new version made a fix

**Comment by akashpandey2193** [comment]
@rnwonder I just ran into a issue where i upgraded to the latest version of datepicker in my project but depending on the theme (specifically dark) on my mac os there are certain styles that are applying globally to my project which are causing certain fields to not show up entirely along with introducing black scroll which was not a case with the previous versions. Can you help me with this please?

**Comment by rnwonder** [comment]
upgrade and see if its still there @akashpandey2193

**Comment by rnwonder** [comment]
What exactly is the issue? The latest version is 1.2.1 by the way

**Comment by Nsj94** [comment]
i am using 1.2.1 still the issue is same.. @rnwonder 

Issue occurs when i use dark mode in my system.. it uses that dark mode setting but in my project i want to use only light mode for ui consistency.
Due to css mentioned in nodemodules of the library , it is messing up...

**Comment by yatin-007** [comment]
@rnwonder I am also facing this issue of the date picker. It is changing my project global styles, especially when using dark mode in my system

**Comment by akashpandey2193** [comment]
@rnwonder the issue exactly is it takes up the style from the os and sets the color-scheme: dark; Once set to dark the styles start interferring with my web application and applies a set of css that is causing the issue with my project once I start using the datepicker.

**Comment by Nsj94** [comment]
Fixed for me too @rnwonder  Thanks

**Comment by fm-buildinformed** [comment]
Using version 1.2.2 the package still sets things such as button background-color globally as soon as I import it anywhere. Unless some hiddne steps are required to fix this, I would not consider this solved.

**Comment by rnwonder** [comment]
@fm-buildinformed what color is being set globally to your buttons. Be more specific

**Comment by fm-buildinformed** [comment]
Hi again, it globally sets the background of my buttons to transparent

```CSS
button, [type="button"], [type="reset"], [type="submit"] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
```

According to chrome these properties come from 
`node_modules/.pnpm/@rnwonder+solid-date-picker@1.2.2_solid-js@1.8.10/node_modules/@rnwonder/solid-date-picker/dist/style.css`

Have a nice day

**Comment by ANovokmet** [comment]
It would be useful if we could choose not to load the CSS. 

For me, the date picker styles are not conflicting with the rest of the application but I am not using Tailwind and hate to see all the variables now appearing in my app. I also need to completely change the style of the buttons (by applying the 'button' class, I am using bulma), so the styles applying to the buttons are not needed for my app.

I don't know of another way to do it so I have Vite configured to exclude CSS like this: 

`vite.config.js`
```js
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
  plugins: [
    solidPlugin(),
    {
      name: 'exclude-date-picker-css',
      load(id, options) {
        if (/^.*\@rnwonder\/solid-date-picker\/.*\.css$/.test(id)) {
          return '';
        }
      }
    }
  ],
});
```
