### ISSUE TITLE
Need to add shouldCloseOnSelect to TimePicker

### ISSUE THREAD

**Issue by vavilen84** [rnwonder/solid-date-picker#16]
Is it possible to add shouldCloseOnSelect to TimePicker (like it is implemented in DatePicker) because popup is not closed when time is already choosen. Looks wierd. Thank you.

**Comment by rnwonder** [comment]
I will look into it in a bit

**Comment by rnwonder** [comment]
Upgrade to the latest version added `shouldCloseOnSelect`  to `TimePicker`

**Comment by vavilen84** [comment]
@rnwonder Thank you!
