### ISSUE TITLE
Light theme is not available

### ISSUE THREAD

**Issue by mansurhamidov14** [rnwonder/solid-date-picker#21]
**Describe the bug**
Light theme is not available

**To Reproduce**
I run my OS system in dark mode. No matter even if I am switching to light mode or I switch theme within my application with switching `class` attribute of `html` element datepicker remains dark

**Expected behavior**
Datepicker should be light

**Screenshots**
![image](https://github.com/rnwonder/solid-date-picker/assets/34154535/796f3c3d-5dd1-4306-9ae7-71bae4af865e)

**Comment by rnwonder** [comment]
Should be fixed now upgrade to the latest version
