### ISSUE TITLE
When we click on Datepicker to open why It calls OnChange,setValue ,OnValueChange Function ?

### ISSUE THREAD

**Issue by thinkClearNarinder** [rnwonder/solid-date-picker#25]
**Describe the bug**
When we click on Datepicker to open it , calls OnChange,setValue ,OnValueChange Function ?

**To Reproduce**
Click on Datepicker and console log inside any of the above function it calls automatically

**Expected behavior**
- It should call these function when we open or close atleast 

**Screenshots**
![Screenshot 2024-03-20 at 5 30 23 PM](https://github.com/rnwonder/solid-date-picker/assets/162269241/a82066ea-064a-497c-a0e3-59b929442133)

**Comment by imgaur3** [comment]
ohh you were also using that you need to be desperate for that.

**Comment by codewithaadi** [comment]
I am also facing the same issue, Clicking the Datepicker triggers automatic calls to OnChange, setValue, and OnValueChange functions. Expected behavior would be for these functions to only execute upon opening or closing the Datepicker.

**Comment by rnwonder** [comment]
Upgrade to the latest version. See if its fixed...

**Comment by thinkClearNarinder** [comment]
@rnwonder Thanx It's Fixed.
