### ISSUE TITLE
compatible：

### ISSUE THREAD

**Issue by 17359898647** [rnwonder/solid-date-picker#33]
**Describe the bug**
Compatibility issues with safari browser

**To Reproduce**
Open the month or year selector to see the style exception

**Screenshots**
<img width="319" alt="image" src="https://github.com/rnwonder/solid-date-picker/assets/58617090/9301dd09-4276-4400-95cd-ffbb1c0ed259">
<img width="364" alt="image" src="https://github.com/rnwonder/solid-date-picker/assets/58617090/2fa09343-a5e9-4f94-8527-3040ca7cdd2a">

**Additional context**
It can be solved in this way
<img width="265" alt="image" src="https://github.com/rnwonder/solid-date-picker/assets/58617090/409fda85-64b8-435d-831f-ac2ece7f5af9">

**Comment by rnwonder** [comment]
Hmm does this happens any where else or just the selectors?

**Comment by rnwonder** [comment]
upgrade to latest version, see if its fixed

**Comment by 17359898647** [comment]
> Hmm does this happens any where else or just the selectors?嗯，这种情况会发生在其他地方还是只发生在选择器上？

It currently only appears when safari clicks on the month or year selector,

**Comment by 17359898647** [comment]
> upgrade to latest version, see if its fixed

It was not fixed in the latest 1.5.6

**Comment by rnwonder** [comment]
upgrade again should be fixed now

**Comment by 17359898647** [comment]
The issue was resolved in version 1.5.7. Has the height been set to automatic?

**Comment by rnwonder** [comment]
yes
