### ISSUE TITLE
If you select a date within 100, there will be a problem,

### ISSUE THREAD

**Issue by 17359898647** [rnwonder/solid-date-picker#34]
**Describe the bug**

https://github.com/user-attachments/assets/03b521a0-0ca1-419f-ae9f-44a5bceaf239

**Comment by rnwonder** [comment]
Thank you! The problem comes from JavaScript Date API. When using the Date constructor in JavaScript with a year value below 100, it interprets the year as an offset from 1900. 

I have fix it in v1.3.9! upgrade and let me know if it works for you
