### ISSUE TITLE
When "startingMonth" is zero, an exception occurs. 

### ISSUE THREAD

**Issue by 17359898647** [rnwonder/solid-date-picker#35]
**Describe the bug**
When "startingMonth" is zero, an exception occurs. 

**Expected behavior**

**Screenshots**

<img width="1339" alt="image" src="https://github.com/user-attachments/assets/14e8c332-8e43-402c-bae8-ca483105955e">
<img width="644" alt="image" src="https://github.com/user-attachments/assets/8b7da0c4-0d4a-4fef-b611-8c41d9ccc011">
<img width="647" alt="image" src="https://github.com/user-attachments/assets/30c09e74-9864-4c1a-8245-b5c061f7924b">

**Comment by rnwonder** [comment]
Should be fixed now upgrade to the new version

**Comment by 17359898647** [comment]
> Should be fixed now upgrade to the new version

Thank you
