### ISSUE TITLE
Unknown file extension ".css"  - Solid Start

### ISSUE THREAD

**Issue by jmoorer** [rnwonder/solid-date-picker#8]
**Describe the bug**
When trying to use this library with solid-start,  I get the follow message:
`Unknown file extension ".css" for {...}/node_modules/@rnwonder/solid-date-picker/dist/style.css`

**To Reproduce**
1. create a solid start project with srr on  https://start.solidjs.com/getting-started/project-setup

2. npm i @rnwonder/solid-date-picker
3. Render a  <DatePicker/> component

**Comment by rnwonder** [comment]
Can you add more context? 
- What version are you using?
- Add a code snippet of how you used it

Note However, In Solid Start you want to render the Datepicker component as client only refer to this [issue](https://github.com/rnwonder/solid-date-picker/issues/3) for more information

**Comment by jmoorer** [comment]
The version I am using     "@rnwonder/solid-date-picker": "^0.7.3",
with   "solid-start": "^0.2.26"
Here is how I am using it
```jsx
import DatePicker,{ PickerValue } from "@rnwonder/solid-date-picker";

  const [value, setValue] = createSignal<PickerValue>({
    value: {},
    label: "",
  });
 <DateTimePicker
      value={value}
      setValue={setValue}
      type="single"
      onChange={(data) => {
        if (data.type === "single") {
          console.log(data.selectedDate);
        }
      }}
      inputProps={{
        ...props,
        class: classNames(
          "input input-bordered w-full max-w-x",
          props.class
        ),
      }}
    />

```

Just added `unstable_clientOnly` locally and it works.  Thanks for the help.  Please keep up the good work.
